baseURL = 'https://jolly-rosalind-278310.netlify.app/'
languageCode = 'en-us'
title = 'Dinsey Villains'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


[params]
  custom_css = ["css/custom.css"]
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  background_color_class = "bg-black"
  featured_image = '/images/marvel.jpeg'
  plugins_css = ["custom"]

[permalinks]
  singles = "/:title/"