baseURL = 'https://jolly-rosalind-278310.netlify.app/'
languageCode = 'en-us'
title = 'Dinsey Villains'
theme = 'ananke'

[params]
  custom_css = ["css/custom.css"]
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  background_color_class = "bg-black"
  featured_image = '/images/marvel.jpeg'
